### ISSUE TITLE
config.ini 在哪生成？

### ISSUE THREAD

**Issue by jjjjohnson** [dingyuqing05/trt2022_wenet#2]
你好 非常棒的项目！
请教一下 [这里](https://github.com/dingyuqing05/trt2022_wenet/blob/2cd7b27155752d2273fc5fd89567d8f3157cdd07/trt_ft_wenet/src/fastertransformer/models/wenet/WenetDecoderWeight.cc#L160)用到的 config.ini 文件是哪里生成的？

谢谢！

**Comment by dingyuqing05** [comment]
这里没有使用ini文件。
代码中，如果ini文件读取失败的话，getModelFileType函数会返回默认的fp32。
因为保存bin时是按照fp32保存的，所以这个地方没有ini也会使用默认的fp32去读权重。
loadWeightFromBin函数会将bin中的fp32类型转成要用的类型T

**Comment by jjjjohnson** [comment]
谢谢解答！
